### ISSUE TITLE
How to populate Instance?

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [SierraSoftworks/Iridium#34] opened 2016-05-15 22:08 UTC
I have User Instance class:

```typescript
class User extends Instance {
    @Property(true)
    name:string

    @Property([User])
    friends:User[]
}
```

when i add user to friend list to another user, and try to save:

```
    firstUser.friends.push(newUser)
    firstUser.save() //error
```

I get recursion error:

![image](https://cloud.githubusercontent.com/assets/17149958/15271749/14304edc-1a61-11e6-9e6b-21b9fd649f6e.png)

P.S. of course firstUser !== newUser and they have different ids

**Comment by SPARTAN563** [comment] 2016-05-16 04:35
Hi Ivan,

Iridium doesn't provide support for nested instances at the moment (and it isn't something which is planned, due to the ease with which you can seriously hurt the performance of a MongoDB system). My recommendation would be to change to something like this instead.

```typescript
class User extends Instance {
    @Property(true)
    name:string

    @Property([string])
    friends:string[]
}
```

You'd then store an array of user IDs for the friends property as follows:

```typescript
firstUser.friends.push(newUser._id)
firstUser.save() //error
```

If you then wished to simplify getting the list of friends, I'd recommend adding a helper function to your instance like this:

```typescript
class User extends Instance {
    constructor(private model: Iridium.Model<UserDoc, User>, document: UserDoc, isNew?: boolean, isPartial?: boolean) {
        super(model, document, isNew, isPartial)
    }

    @Property(true)
    name:string

    @Property([string])
    friends:string[]

    fetchFriends(): Promise<User[]> {
        return this.model.find({ _id: { $in: this.friends.map(Iridium.toObjectID) } }).toArray()
    }
}
```

The advantage of this approach is that it ensures you don't perform the join automatically at any point, hurting performance in situations where you need a user but don't require their friends. It also makes it a bit more visible that you are performing a database operation, helping new developers understand where potential bottlenecks are in the codebase.

Let me know if you need anything else or if I can help out in another way.

Regards,
Benjamin

**Comment by uMaxmaxmaximus** [comment] 2016-05-16 11:20
Make a special api for such purposes, to such frequent and widespread problem, it would be possible to describe the apparent and invented your way =)

No?

**Comment by SPARTAN563** [comment] 2016-05-16 12:18
I can definitely take a look, I was considering doing it using a plugin which would enable opt-in support of that functionality and help avoid people accidentally causing performance issues.

In this case though, I'm less worried about CPU load and far more about memory usage. For example, if we follow the idea of ["six degrees of separation"](https://en.wikipedia.org/wiki/Six_degrees_of_separation) and you happened to have the entire world's population in your database - then the recursive nature of the query will result in you pulling your entire user database into memory for each and every user. Combine that with the fact that Iridium doesn't de-duplicate instances in memory and you'll quickly run out.

I like the `async get friends() { }` approach, and I think really what needs to be done is making it easy to access your database context from within your model hooks - enabling adding these nice and easily. The only issue is that it can be tricky to pass that information through while keeping the API nice and simply (I'm referring to the types now).

I'll take a look when I get the chance, and let you know when I have something which can work.

**Comment by uMaxmaxmaximus** [comment] 2016-05-16 12:20
want, I can help you?

**Comment by SPARTAN563** [comment] 2016-05-16 12:32
You're more than welcome to, there's a couple of things to keep in mind when investigating solutions - specifically the following:

1. The API should remain backwards compatible (if you don't need to modify existing tests then you're good).
2. It should be an opt-in feature, rather than opt-out. Iridium strives to start you off in a position from which good performance is easy, if you want to degrade it then you should be made aware of that fact. (A plugin is a great way to achieve this)
3. It should ideally be semantically similar to how you'd write the code if you weren't using Iridium - users should be able to understand the code without using the docs.

With that in mind, let's start with what we'd be looking to achieve, after that we'll think about how we'd want to use it (our ideal API) and then whether that's possible given the constraints of the language and framework (i.e. what concessions we need to make in order to implement it).

Before you get too invested in the concept however, I'm apprehensive about adding it (especially to the core library) since it will likely bring with it a bunch of added complexity, something I'm looking to avoid in the codebase.

## Goals

1. Enable users to transparently create relationships by specifying `Iridium.Instance` types in the schema.
2. Automatically retrieve related entities and surface them using the corresponding schema property.
3. Store related entities using a join key (`_id` should work).
4. Recursively save changes to related entities when a parent is saved.
5. Support for many-* relationships using `[Iridium.Instance]` as the schema type.

Let me know if you can think of anything else which you'd like to see addressed by this

**Comment by uMaxmaxmaximus** [comment] 2016-05-18 05:30
how to assecc to parent model from Instance? this._model is private (not protected)

this code not compile
```typescript
    fetchFriends(): Promise<User[]> {
        return this.model.find({ _id: { $in: this.friends.map(Iridium.toObjectID) } }).toArray()
    }
```

**Comment by SPARTAN563** [comment] 2016-05-18 05:33
Hi Ivan,

You'll see that I've added a new constructor in my code example which exposes the model within your local scope as well as `this.model`.

If that's not the error you're getting, could you send the error message to me so I can help diagnose the cause, the code I gave you there just being off the top of my head.

**Comment by uMaxmaxmaximus** [comment] 2016-05-18 05:46
Oh sure, I have noticed. By the way, it is already working, and it's great, it's amazing, it's delicious, it is divine, it is paradoxically:

![image](https://cloud.githubusercontent.com/assets/19378179/15348558/80063246-1cd4-11e6-9314-d72cee919699.png)

The only thing is I have a name conflict occurs between `get friends () {}` and field `friends: [String]`, sorry decorator can not rename a field. Then I could replaced the box friends on _friends, and hung it on a getter friends

**Comment by uMaxmaxmaximus** [comment] 2016-05-18 05:50
Oh, I came up with: We need to change the implementation of the decorator @Property

![image](https://cloud.githubusercontent.com/assets/19378179/15348709/959388a6-1cd5-11e6-9361-b0d39df37aa5.png)

**Comment by uMaxmaxmaximus** [comment] 2016-05-18 05:51
Oh, I came up with: We need to change the implementation of the decorator @Property

![image](https://cloud.githubusercontent.com/assets/19378179/15348709/959388a6-1cd5-11e6-9361-b0d39df37aa5.png)

**Comment by uMaxmaxmaximus** [comment] 2016-05-18 05:57
Oh, I came up with: We need to change the implementation of the decorator @Property

![image](https://cloud.githubusercontent.com/assets/19378179/15348709/959388a6-1cd5-11e6-9361-b0d39df37aa5.png)

It should scan, and if the arguments referred to it as the type specified class that inherits from the Instance class, then we must do the following:

We must as the name of the database used to use the `_friends` as a property` friends` hang getter

**Comment by uMaxmaxmaximus** [comment] 2016-05-18 06:04
```typescript
        let firstUser = await this.list.get()
        let friends = await firstUser.friends
        friends.push(firstUser)
        firstUser.save() // ????
```


What do we do in such a situation? probably worth somewhere to keep the old version of the array, and returns a new, and while maintaining compare them, then find change, convert Instances in ObjectId and push them property `_friends` (array string ids) and save

**Comment by SPARTAN563** [comment] 2016-05-18 07:32
Hi Ivan,

I'd rather not change the way `@Property` works simply because it's likely to break other things, however let's look at a way this could be accomplished using the existing infrastructure (specifically the `@Property`, `@Transform` and `@Validator` decorators and tooling). For example, it may be possible to do something like this:

```typescript
class User extends Instance<UserDoc, User> {
  
  @InstanceProperty<MyIridiumCore, User>(core => core.User)
  get friends(): Promise<User[]> {
    return Promise.reject(new Error("implemented by Iridium"));
  }
}
```

It could then rewrite (thanks to the decorator) into something like this:

```typescript
class User extends Instance<UserDoc, User> {
  @Schema([string])
  private _friends: User[] = [];
  private _friendsModel: Model<UserDoc, User>;
  
  get friends(): Promise<User[]> {
    return this["_friendsModel"].find({ _id: { $in: this["_friends"].map(x => toObjectID(x)) } });
  }
}
```

However I don't like that solution much for the following reasons:

1. There's "magic" going on, it writes "code" at runtime which you'll never see and as a result it's likely to cause a bunch of confusion.
2. It doesn't allow you to modify the friends list, and adding an `addFriend(user: User)` method automatically will not expose it to TypeScript, which defeats the purpose.
3. It isn't immediately obvious what the implemented code does - `return Promise.reject(...)` never gets called and it's likely to confuse someone who isn't familiar with the codebase.
4. Changes made to users returned from `instance.friends` will not be saved when you call `instance.save()` - which will result in developers losing changes they've made.

One can work around most of this by using hooks, but then we get back to the issue of recursively fetching your entire datastructure - something which will hurt performance...

An example of the hook solution is this:

```typescript
interface UserDoc {
  _friends?: string[];
}

class User extends Instance<UserDoc, User> implements UserDoc {
  _friends: string[] = [];
  friends: User[] = [];

  static onSaving(doc: UserDoc, changes: any) {
    changes.$set = changes.$set || {};
    changes.$set["_friends"] = doc.friends.map(x => x._id);
  }

  static onReady(instance: User) {
    return db.User.find({ _id: { $in: instance._friends.map(x => Iridium.toObjectID(x)) } }).toArray().then(friends => {
      instance.friends = friends;
    });
  }
}
```

Of course, as I mentioned earlier, it will always recursively fetch every single user - and it's naive when it comes to things like circular references - which will mean it quickly gets into an infinite loop and will crash.

**Comment by uMaxmaxmaximus** [comment] 2016-05-18 23:14
Recursive references are handled by the buffer, it is strange that you did not know:

````javascript
function wrapObj(obj, buffer = []){
    if(buffer.instanceOf(obj) !== -1) return obj;
    //reqouese
    wrapObj(childObоб buffer)
}
````

**Comment by SPARTAN563** [comment] 2016-05-19 04:37
Buffers are certainly one solution, however they introduce their own problems (specifically around the guarantees that Iridium makes regarding instances). Specifically that each instance returned by its API is distinct and that changes made to one will not affect others. This is an important aspect to consider when building async systems as conflicts can result in garbled data being inserted into the database.

An additional problem with using a buffer is that it gets in the way of the garbage collector doing its job, since the buffer (generally a Map object) holds a reference to each instance, it becomes impossible for the GC to collect those instances when you're finished working with them. This can quickly lead to runaway memory usage, especially in systems which process a large amount of data (I've got some which move 10s of GB of data per day through Iridium - something like that would make the system unusable and unscalable).

I'll take a look at OrientDB, however at this point I'm not sure that I'll have the time to put together and maintain another ORM, especially when Iridium fulfils my requirements perfectly at the moment (lightweight, fast, simple to use and predictable). That being said, if you're interested in starting a project and would like someone in the field to bounce ideas off, I'd be more than happy to help out.

**Comment by uMaxmaxmaximus** [comment] 2016-05-19 05:33
As I understand it has a built OrientDB OOP, and we need write just a nice wrapper. Similar to Iridium for example.

**Comment by SPARTAN563** [comment] 2016-05-19 05:36
Well you could certainly try forking Iridium and changing it to support their query language, however it's worth keeping in mind that Iridium is very much designed to replicate the standard MongoDB command line API - you'd probably want to create something which is more similar to the OrientDB library API if you were to implement your own.

**Comment by uMaxmaxmaximus** [comment] 2016-05-19 06:48
https://github.com/gabipetrovay/node-orientdb/wiki/Blog-Tutorial-with-ExpressJS-and-OrientDB
https://github.com/orientechnologies/orientjs

I want create JavaScript ORM over OrientDB nodejs driver =)
ORM in Iridium style. I start write in 6 days

**Closed** 2016-05-19 16:49 UTC
