### ISSUE TITLE
instance properties

### ISSUE THREAD

**Issue by SET001** [SierraSoftworks/Iridium#40] opened 2016-06-11 21:31 UTC
After I create an instance of some model I can't read it's properties directly in instance, they are in `acc.document`. But wen I do `Model.findOne` in it's callback I got a `TInstance` object with all properties accessible directly in this object and also in `TInstance.document`:

```
var acc = new AccountInstance(authModule.storage.Accounts, {
	login: 'testUser'
});
console.log(acc.login);  // undefined
console.log(acc.document.login);  // 'testUser'
authModule.storage.Accounts.findOne().then((acc)=>{
	console.log(acc.login);  // 'testUser'
	console.log(acc.document.login);  // 'testUser'
	done();
});
```

Is this a bug or am I missing something?  Is it possible to always have all properties in `TInstance's` root?

**Comment by SPARTAN563** [comment] 2016-06-12 07:53
Hi Konstantin,

I suspect you haven't registered your properties with the schema, for optimization reasons, Iridium doesn't redefine the prototype for each document it receives (that forces V8 to deoptimize code which uses your instances and can significantly hurt performance, not to mention creating a new prototype for each document it receives). 

Your account instance should look something like this:

```javascript
@Iridium.Collection("accounts")
class AccountInstance extends Iridium.Instance {
  @Iridium.Property(String)
  login = null
}
```

The `login = null` is required to allow the property decorator to trigger in some situations, as you can see in #38.

**Comment by SET001** [comment] 2016-06-12 08:57
my account instance looks like this:

I have updated my instance class to look like this:

```
@Index({ name: 1 })
@Collection('accounts')
export class AccountInstance extends Instance<Account, AccountInstance> implements Account{
	@ObjectID _id: number;
	@Property(String) password: string = 'defaultValue'
	@Property(String) login: string = 'defaultValue'
	@Property(String) email: string = 'defaultValue'
	@Property(Number) lastSeenDate: number = 9999
	@Property(String) lastSeenIp: string = 'defaultValue'
}
```

now the code from OP give such a results: 

```
====> defaultValue
====> testUser
====> defaultValue
====> defaultValue
```

which mean that default values are not overwritten by `findOne`

So back to my first question, is it right that I should always access instance properties through `document`?

**Comment by SPARTAN563** [comment] 2016-06-12 17:21
Hi Konstantin,

Sorry about that, I neglected to mention that ES6 default values currently don't work as intended (something I'm looking to fix, but haven't had the chance to yet). If you'd like to setup default values, currently the best approach is to use the `onCreated()` callback.

```typescript
@Index({ name: 1 })
@Collection('accounts')
export class AccountInstance extends Instance<Account, AccountInstance> implements Account{
    @ObjectID _id: number;
    @Property(String) password: string
    @Property(String) login: string 
    @Property(String) email: string
    @Property(Number) lastSeenDate: number
    @Property(String) lastSeenIp: string

    static onCreated(doc: Account) {
        doc.password = doc.password || 'defaultValue'
        doc.login = doc.login || 'defaultValue'
        // ...etc
    }
}
```

I also just realized that I'd missed something when answering your first question. I see you're instantiating your instance class directly, in which case you're correct that it won't make the properties available - the properties are exposed by a transparent proxy class which the model generates (this is done to allow V8 to optimize property accessors and type interfaces) - if you'd like to manually instantiate a version of your instance then you should do this instead:

```typescript
var AccountModel = new Model<Account, AccountInstance>(db, AccountInstance)

var acc = new AccountModel.Instance({ login: 'testUser' })
console.log(acc.login) // 'testUser'
```

**Comment by SET001** [comment] 2016-06-19 15:34
if I create instance like in you last example:

```
var acc = new AccountModel.Instance({ login: 'testUser' })
```

and then save it using `acc.save()` it will create new document in database. But if I then at some step will make any changes to `acc` and save it again, I would get error 

`Unhandled rejection MongoError: E11000 duplicate key error collection:`

which looks like it tries to create new document, instead of update existing.

7.0.0-alpha.8

**Comment by SPARTAN563** [comment] 2016-06-20 16:44
Hi Konstantin,

I'll quickly take a look and get back to you

**Comment by SPARTAN563** [comment] 2016-06-20 17:42
Hi Konstantin,

I've put together a test which does what you describe, however I've not seen the behaviour you're describing. Could you please take a look and see if there's anything different you're doing, and if so, let me know so we can try and find a solution?

**Comment by SET001** [comment] 2016-06-21 18:16
I updated to 7.0.0-alpha.10  but still have this issue. While I'mt trying to understand the difference between my case and your test I found that one of tests is failing

```

  358 passing (3s)
  1 failing

  1) Core connect should return a rejection if the connection fails:
     AssertionError: expected promise to be rejected but it was fulfilled with { Object (mongoConnectAsyc, _plugins, ...) }
      at .<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:126:55)
      at .<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:70:33)
      at addProperty (node_modules/chai/lib/chai/utils/addProperty.js:43:29)
      at Context.<anonymous> (dist/test/Core.js:200:57)



npm ERR! Test failed.  See above for more details.
```

**Comment by SET001** [comment] 2016-06-21 18:19
for now I can only say that `.isNew` is set to true before and after `save()`

**Comment by SPARTAN563** [comment] 2016-06-21 19:01
Interesting, looks like your OS is resolving `0.0.0.0` when I had assumed it wouldn't (and it hadn't done so on any of my test systems). Not the end of the world at all, just curious.

I'm highly concerned about why `._isNew` is `true` before **and after**, is there the possibility that you aren't awaiting the completion of the `save()` operation before proceeding?

**Comment by SET001** [comment] 2016-06-21 19:20
Yeah, my fault. I was neglected the fact that save is asynchronous. Sorry for wasting your time and thanx for support.

**Comment by SPARTAN563** [comment] 2016-06-21 19:25
No worries at all, glad you've found the solution :smile:

**Closed** 2016-06-21 19:46 UTC
